services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        env_file: .env
        volumes:
            - './apps/csv_db:/usr/src/app'
            - './data:/usr/src/app/private/data'
            - '.env:/usr/src/app/.env'
        restart: unless-stopped
        command: [ "php-fpm" ]
        depends_on:
            mysql_db:
                condition: service_healthy
    nginx:
        image: nginx:1.21.3-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./apps/csv_db/public:/usr/src/app/public
        restart: unless-stopped
        depends_on:
            - php-fpm
    mysql_db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        restart: unless-stopped
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: [ CMD, mysqladmin, ping, --silent ]
        ports:
            - 3306:3306
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
volumes:
    db:
